# Generated by Django 2.2 on 2020-12-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
